### ISSUE TITLE
Option to suppress output currently shown to standard out

### ISSUE THREAD

**Issue by cboettig** [ropensci/appl#2]
The standard out information is usually useful, but sometimes the user will want to suppress this.  Would be good to have a `silent=FALSE` option for `pomdpsol`

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/ropensci/appl/commit/5265f7e514b1796d30724144b2ee13b9d18bfaf1. You can now suppress output by setting `stdout = FALSE`.
