### ISSUE TITLE
covr::package_coverage fails?

### ISSUE THREAD

**Issue by cboettig** [ropensci/appl#5]
Hey @jeroenooms ,
cc @jimhester,

Was just trying to add codecov integration to the `.travis.yml` and noticed that `covr` is failing to run on this package.  Any idea why?  I get the error:

```r
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘/home/rstudio/Documents/research/code/cboettig/appl’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/RtmpGCltYv/R_LIBS872e8d8e0/appl/R/appl': No such file or directory
```

Seems like it is failing to install the package in the first place; perhaps because `covr` is doing something fancy when it compiles the C code in order to try and measure C code coverage? (Maybe there's a way to exclude measuring C code coverage anyhow, but  I couldn't find it).

**Comment by jeroenooms** [comment]
Can you `traceback()` where this ` file(con, "r")` originates?

**Comment by jimhester** [comment]
It is failing when trying to install the package with `--coverage`. You had a typo `CXXLAGS` should be `CXXFLAGS`.

If you ever see coverage errors try running `coverage <- covr::package_coverage(quiet = F)` locally to diagnose what is going on.
